### ISSUE TITLE
Seperete proxy addon/container

### ISSUE THREAD

**Issue by pergolafabio** [vanackej/risco-mqtt-local#54]
Hey @vanackej 

Local is coming verry soon to HA as an official integration , thnx to OnFreund
https://github.com/home-assistant/core/pull/75874

But it lacks a proxy....

Can you help me setting up just an addon to act as a proxy? nothing more, nothing less, so we can make use of the official integration, witt our older boards ( cloud enabled )

The proxy is already part of this addon, would be great if you can split it up into a new addon

Or if you can give me a hand so can start with it?

much appreciated

**Comment by vanackej** [comment]
Unfortunately that's not that simple. The architecture of the
communications don't allow to combine the official local integration with
just an external 'proxy'. In fact the whole connection flow is different in
proxy mode. You can't have the official local integration connecting to the
panel and another process running a proxy and waiting for panel connection
=> it would imply that your panel must manage 2 socket connections, which
is exactly what is not supported by your panel.

So I'm afraid it won't be possible.

Best options : either don't use risco cloud,  upgrade your TCP module, or
keep using this addon instead of the official one

Le mer. 17 août 2022 à 09:41, pergolafabio ***@***.***> a
écrit :

**Comment by pergolafabio** [comment]
ok, thx for feedback, i sill with the local addon for now
